name: Parallel Cypress Tests

on: [push]

jobs:
  test1:
    name: Cypress run(1)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/**.js  
  test2:
    name: Cypress run(2)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/BB/**.js  
  test3:
    name: Cypress run(2)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/AA/**.js                  
  

