name: included

on: [push]

jobs:
  
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:9.5.1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - run: | 
          docker build -t cyp-dock .
      - run: | 
          docker-compose up       
