# parallelization throght  
name: Cypress Tests

on: [push]

concurrency:
    group: main-pipeline-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 4 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:          
          CYPRESS_RECORD_KEY: "${{ secrets.CYPRESS_RECORD_KEY }}"
          CYPRESS_PROJECT_ID: "${{ secrets.PROJECT_ID }}"


# Github action work flow to run docker file
#name: Cypress Tests

#on:
 # pull_request: [release]

#concurrency:
    #group: cypress-pipeline-${{ github.head_ref }}
    #cancel-in-progress: true

#jobs:
  #cypressTest:
    #runs-on: ubuntu-latest
    #steps:
     # - name: Checkout
      #  uses: actions/checkout@v2
      #- run: npm ci
      #- run: | 
       #   docker build -t cy-img-dock .
      #- run: | 
       #   docker-compose up   


# multi Jobs work parallel 
# each Job run specific tests 
name: Cypress Tests
on: [push]

jobs:
  test1:
    name: Cypress run(1)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/foldername/**.js  
  test2:
    name: Cypress run(2)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/foldername/**.jsx  
  test3:
    name: Cypress run(2)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/foldername/**.jsx