name: Cypress Tests

on: [push]

concurrency:
    group: main-pipeline-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 4 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:          
          CYPRESS_RECORD_KEY: "${{ secrets.CYPRESS_DASHBOARD_RECORD_KEY }}"
