name: included
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:9.5.1
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cyp-dock .


