name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          spec: |
            cypress/integration/**.spec.js
            cypress/integration/AA/**.spec.js    


  cypress-run2:
    name: Cypress run2
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with: 
          spec: |
            cypress/integration/BB/**.spec.js        
